spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:survivordb
    username: sa
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      indent-output: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
